In [23]:
import pandas as pd
import numpy as np

In [24]:
dos_data = pd.read_csv("data/DoS_dataset.csv",nrows=90,header=None)

In [25]:
col_names = ['time_stamp','id', 'dlc','d0','d1','d2','d3','d4','d5','d6','d7','R']

In [26]:
dos_data.columns = col_names

In [27]:
dos_data.head()

time_stamp    id  dlc  d0  d1  d2  d3  d4  d5  d6  d7  R
0  1.478198e+09  0316    8  05  21  68  09  21  21  00  6f  R
1  1.478198e+09  018f    8  fe  5b  00  00  00  3c  00  00  R
2  1.478198e+09  0260    8  19  21  22  30  08  8e  6d  3a  R
3  1.478198e+09  02a0    8  64  00  9a  1d  97  02  bd  00  R
4  1.478198e+09  0329    8  40  bb  7f  14  11  20  00  14  R

In [28]:
dos_data.tail()

time_stamp    id  dlc  d0  d1  d2  d3  d4  d5  d6  d7  R
85  1.478198e+09  0131    8  05  80  00  00  46  7f  0f  c8  R
86  1.478198e+09  0140    8  00  00  00  00  10  28  2f  01  R
87  1.478198e+09  0350    8  05  20  54  68  77  00  00  6e  R
88  1.478198e+09  043f    8  00  40  60  ff  7e  c9  08  00  R
89  1.478198e+09  0370    8  00  20  00  00  00  00  00  00  R

In [29]:
dos_data = dos_data.drop(['time_stamp', 'dlc','R'], axis=1)
dos_data.head()

id  d0  d1  d2  d3  d4  d5  d6  d7
0  0316  05  21  68  09  21  21  00  6f
1  018f  fe  5b  00  00  00  3c  00  00
2  0260  19  21  22  30  08  8e  6d  3a
3  02a0  64  00  9a  1d  97  02  bd  00
4  0329  40  bb  7f  14  11  20  00  14

In [30]:
dos_data_int = dos_data.head(n=30)

In [31]:
dos_data_int.id.apply(int, base=16)

0      790
1      399
2      608
3      672
4      809
5     1349
6        2
7      339
8      704
9      304
10     305
11     320
12     848
13    1087
14     880
15    1088
16     790
17     399
18     608
19     672
20     809
21    1264
22    1349
23    1072
24    1201
25     497
26     339
27       2
28     704
29     848
Name: id, dtype: int64

In [32]:
temp_np = dos_data_int.to_numpy()

In [33]:
n = 30
m = 9

tem_file = np.zeros([n,m])
tem_file

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0.

In [34]:
temp_np = dos_data_int.to_numpy()

In [35]:
for i in range(n):
    line = []
    for j in range(9):
        num = int(temp_np[i][j],base=16)
#         print(num)
        line.append(num)
    tem_file[i] = np.array(line,dtype=np.int32)     

In [36]:
tem_file

array([[ 790.,    5.,   33.,  104.,    9.,   33.,   33.,    0.,  111.],
       [ 399.,  254.,   91.,    0.,    0.,    0.,   60.,    0.,    0.],
       [ 608.,   25.,   33.,   34.,   48.,    8.,  142.,  109.,   58.],
       [ 672.,  100.,    0.,  154.,   29.,  151.,    2.,  189.,    0.],
       [ 809.,   64.,  187.,  127.,   20.,   17.,   32.,    0.,   20.],
       [1349.,  216.,    0.,    0.,  138.,    0.,    0.,    0.,    0.],
       [   2.,    0.,    0.,    0.,    0.,    0.,    3.,   11.,   17.],
       [ 339.,    0.,   33.,   16.,  255.,    0.,  255.,    0.,    0.],
       [ 704.,   20.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [ 304.,    8.,  128.,    0.,  255.,   49.,  128.,   11.,  127.],
       [ 305.,  229.,  127.,    0.,    0.,   72.,  127.,   11.,  172.],
       [ 320.,    0.,    0.,    0.,    0.,    8.,   34.,   43.,  163.],
       [ 848.,    5.,   32.,   20.,  104.,  119.,    0.,    0.,   46.],
       [1087.,    0.,   64.,   96.,  255.,  126.,  206.,    8., 

In [37]:
from PIL import Image
from IPython.display import display

In [38]:
img = Image.fromarray(tem_file, 'L')

In [39]:
display(img)

In [40]:
img.show()

In [41]:
d = {'x':[tem_file],'y':["dos"]}
df = pd.DataFrame(data=d)

In [42]:
df.head()

x    y
0  [[790.0, 5.0, 33.0, 104.0, 9.0, 33.0, 33.0, 0....  dos

In [43]:
df.shape

(1, 2)

In [21]:
df.x[0]

array([[ 790.,    5.,   33.,  104.,    9.,   33.,   33.,    0.,  111.],
       [ 399.,  254.,   91.,    0.,    0.,    0.,   60.,    0.,    0.],
       [ 608.,   25.,   33.,   34.,   48.,    8.,  142.,  109.,   58.],
       [ 672.,  100.,    0.,  154.,   29.,  151.,    2.,  189.,    0.],
       [ 809.,   64.,  187.,  127.,   20.,   17.,   32.,    0.,   20.],
       [1349.,  216.,    0.,    0.,  138.,    0.,    0.,    0.,    0.],
       [   2.,    0.,    0.,    0.,    0.,    0.,    3.,   11.,   17.],
       [ 339.,    0.,   33.,   16.,  255.,    0.,  255.,    0.,    0.],
       [ 704.,   20.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [ 304.,    8.,  128.,    0.,  255.,   49.,  128.,   11.,  127.],
       [ 305.,  229.,  127.,    0.,    0.,   72.,  127.,   11.,  172.],
       [ 320.,    0.,    0.,    0.,    0.,    8.,   34.,   43.,  163.],
       [ 848.,    5.,   32.,   20.,  104.,  119.,    0.,    0.,   46.],
       [1087.,    0.,   64.,   96.,  255.,  126.,  206.,    8., 

In [22]:
dos_data = pd.read_csv("DoS_dataset.csv",header=None)
dos_data.columns = col_names
dos_data.head()

time_stamp    id  dlc  d0  d1  d2  d3  d4  d5  d6  d7  R
0  1.478198e+09  0316    8  05  21  68  09  21  21  00  6f  R
1  1.478198e+09  018f    8  fe  5b  00  00  00  3c  00  00  R
2  1.478198e+09  0260    8  19  21  22  30  08  8e  6d  3a  R
3  1.478198e+09  02a0    8  64  00  9a  1d  97  02  bd  00  R
4  1.478198e+09  0329    8  40  bb  7f  14  11  20  00  14  R

In [23]:
dos_data = dos_data.drop(['time_stamp', 'dlc','R'], axis=1)

In [24]:
dos_data.head()

id  d0  d1  d2  d3  d4  d5  d6  d7
0  0316  05  21  68  09  21  21  00  6f
1  018f  fe  5b  00  00  00  3c  00  00
2  0260  19  21  22  30  08  8e  6d  3a
3  02a0  64  00  9a  1d  97  02  bd  00
4  0329  40  bb  7f  14  11  20  00  14

In [25]:
dos_data.shape

(3665771, 9)

In [26]:
dos_data = dos_data.dropna()
dos_data.shape

(3634583, 9)

In [27]:
def create_feature(data_frame,label,n=30,m=9):
    feature_list = []
    nrow = data_frame.shape[0]
    for col  in dos_data.columns:
        data_frame[col] = data_frame[col].apply(int, base=16)
    for i in range(0,nrow,n):
        if nrow >=  i+n:
            tem_file = data_frame.iloc[i:i+n,:].to_numpy()
            feature_list.append(tem_file)
    feature_df = pd.DataFrame(data={"features":feature_list,"label":[label]*len(feature_list)})
    return feature_df

In [ ]:
dos_feature_df = create_feature(dos_data,"dos")    

In [ ]:
dos_feature_df.head()

In [ ]:
dos_feature_df.shape

In [7]:
fuzzy_data = pd.read_csv("Fuzzy_dataset.csv",sep='delimiter',header=None)
# fuzzy_data.columns = col_names
fuzzy_data.head()

<ipython-input-7-479496432d9d>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  fuzzy_data = pd.read_csv("Fuzzy_dataset.csv",sep='delimiter',header=None)


0
0  1478195721.903877,0545,8,d8,00,00,8a,00,00,00,...
1          1478195721.905736,02b0,5,ff,7f,00,05,49,R
2  1478195721.908437,0002,8,00,00,00,00,00,01,07,...
3  1478195721.908676,0153,8,00,21,10,ff,00,ff,00,...
4  1478195721.909414,0130,8,19,80,00,ff,fe,7f,07,...

In [26]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Ops').getOrCreate()

In [62]:
fuzzy_data = spark.read.csv(
    "DoS_dataset.csv", 
    header=None
)

In [63]:
fuzzy_data.show(n=5)

+-----------------+----+---+---+---+---+---+---+---+---+----+----+
|              _c0| _c1|_c2|_c3|_c4|_c5|_c6|_c7|_c8|_c9|_c10|_c11|
+-----------------+----+---+---+---+---+---+---+---+---+----+----+
|1478198376.389427|0316|  8| 05| 21| 68| 09| 21| 21| 00|  6f|   R|
|1478198376.389636|018f|  8| fe| 5b| 00| 00| 00| 3c| 00|  00|   R|
|1478198376.389864|0260|  8| 19| 21| 22| 30| 08| 8e| 6d|  3a|   R|
|1478198376.390096|02a0|  8| 64| 00| 9a| 1d| 97| 02| bd|  00|   R|
|1478198376.390333|0329|  8| 40| bb| 7f| 14| 11| 20| 00|  14|   R|
+-----------------+----+---+---+---+---+---+---+---+---+----+----+
only showing top 5 rows



In [64]:
from functools import reduce
    
def rename_col(data, col_names=col_names):
    oldColumns = data.schema.names
    data = reduce(lambda data, idx: data.withColumnRenamed(oldColumns[idx], col_names[idx]), 
                        range(len(oldColumns)), data)
    return data


In [65]:
fuzzy_data = rename_col(fuzzy_data)
fuzzy_data.show(n=5)

+-----------------+----+---+---+---+---+---+---+---+---+---+---+
|       time_stamp|  id|dlc| d0| d1| d2| d3| d4| d5| d6| d7|  R|
+-----------------+----+---+---+---+---+---+---+---+---+---+---+
|1478198376.389427|0316|  8| 05| 21| 68| 09| 21| 21| 00| 6f|  R|
|1478198376.389636|018f|  8| fe| 5b| 00| 00| 00| 3c| 00| 00|  R|
|1478198376.389864|0260|  8| 19| 21| 22| 30| 08| 8e| 6d| 3a|  R|
|1478198376.390096|02a0|  8| 64| 00| 9a| 1d| 97| 02| bd| 00|  R|
|1478198376.390333|0329|  8| 40| bb| 7f| 14| 11| 20| 00| 14|  R|
+-----------------+----+---+---+---+---+---+---+---+---+---+---+
only showing top 5 rows



In [66]:
columns_to_drop = ['time_stamp','R']

fuzzy_data = fuzzy_data.drop(*columns_to_drop)
fuzzy_data.show(n=5)

+----+---+---+---+---+---+---+---+---+---+
|  id|dlc| d0| d1| d2| d3| d4| d5| d6| d7|
+----+---+---+---+---+---+---+---+---+---+
|0316|  8| 05| 21| 68| 09| 21| 21| 00| 6f|
|018f|  8| fe| 5b| 00| 00| 00| 3c| 00| 00|
|0260|  8| 19| 21| 22| 30| 08| 8e| 6d| 3a|
|02a0|  8| 64| 00| 9a| 1d| 97| 02| bd| 00|
|0329|  8| 40| bb| 7f| 14| 11| 20| 00| 14|
+----+---+---+---+---+---+---+---+---+---+
only showing top 5 rows



In [67]:
fuzzy_data.count()

3665771

In [68]:
fuzzy_data=fuzzy_data.na.drop()
fuzzy_data.count()

3634583

In [ ]:
from functools import reduce
    
def rename_col(data, col_names=col_names):
    oldColumns = data.schema.names
    data = reduce(lambda data, idx: data.withColumnRenamed(oldColumns[idx], col_names[idx]), 
                        range(len(oldColumns)), data)
    return data

In [69]:
fuzzy_data.show(n=5)

+----+---+---+---+---+---+---+---+---+---+
|  id|dlc| d0| d1| d2| d3| d4| d5| d6| d7|
+----+---+---+---+---+---+---+---+---+---+
|0316|  8| 05| 21| 68| 09| 21| 21| 00| 6f|
|018f|  8| fe| 5b| 00| 00| 00| 3c| 00| 00|
|0260|  8| 19| 21| 22| 30| 08| 8e| 6d| 3a|
|02a0|  8| 64| 00| 9a| 1d| 97| 02| bd| 00|
|0329|  8| 40| bb| 7f| 14| 11| 20| 00| 14|
+----+---+---+---+---+---+---+---+---+---+
only showing top 5 rows



In [1]:
fuzzy_data[2:10,]

NameError: name 'fuzzy_data' is not defined

In [73]:
spark.sql("SELECT * FROM t_fuzzy WHERE row_num between 1 and 2").show()

AnalysisException: cannot resolve '`row_num`' given input columns: [t_fuzzy.d0, t_fuzzy.d1, t_fuzzy.d2, t_fuzzy.d3, t_fuzzy.d4, t_fuzzy.d5, t_fuzzy.d6, t_fuzzy.d7, t_fuzzy.dlc, t_fuzzy.id]; line 1 pos 28;
'Project [*]
+- 'Filter (('row_num >= 1) AND ('row_num <= 2))
   +- SubqueryAlias t_fuzzy
      +- Filter AtLeastNNulls(n, id#1679,dlc#1692,d0#1705,d1#1718,d2#1731,d3#1744,d4#1757,d5#1770,d6#1783,d7#1796)
         +- Project [id#1679, dlc#1692, d0#1705, d1#1718, d2#1731, d3#1744, d4#1757, d5#1770, d6#1783, d7#1796]
            +- Project [time_stamp#1666, id#1679, dlc#1692, d0#1705, d1#1718, d2#1731, d3#1744, d4#1757, d5#1770, d6#1783, d7#1796, _c11#1592 AS R#1809]
               +- Project [time_stamp#1666, id#1679, dlc#1692, d0#1705, d1#1718, d2#1731, d3#1744, d4#1757, d5#1770, d6#1783, _c10#1591 AS d7#1796, _c11#1592]
                  +- Project [time_stamp#1666, id#1679, dlc#1692, d0#1705, d1#1718, d2#1731, d3#1744, d4#1757, d5#1770, _c9#1590 AS d6#1783, _c10#1591, _c11#1592]
                     +- Project [time_stamp#1666, id#1679, dlc#1692, d0#1705, d1#1718, d2#1731, d3#1744, d4#1757, _c8#1589 AS d5#1770, _c9#1590, _c10#1591, _c11#1592]
                        +- Project [time_stamp#1666, id#1679, dlc#1692, d0#1705, d1#1718, d2#1731, d3#1744, _c7#1588 AS d4#1757, _c8#1589, _c9#1590, _c10#1591, _c11#1592]
                           +- Project [time_stamp#1666, id#1679, dlc#1692, d0#1705, d1#1718, d2#1731, _c6#1587 AS d3#1744, _c7#1588, _c8#1589, _c9#1590, _c10#1591, _c11#1592]
                              +- Project [time_stamp#1666, id#1679, dlc#1692, d0#1705, d1#1718, _c5#1586 AS d2#1731, _c6#1587, _c7#1588, _c8#1589, _c9#1590, _c10#1591, _c11#1592]
                                 +- Project [time_stamp#1666, id#1679, dlc#1692, d0#1705, _c4#1585 AS d1#1718, _c5#1586, _c6#1587, _c7#1588, _c8#1589, _c9#1590, _c10#1591, _c11#1592]
                                    +- Project [time_stamp#1666, id#1679, dlc#1692, _c3#1584 AS d0#1705, _c4#1585, _c5#1586, _c6#1587, _c7#1588, _c8#1589, _c9#1590, _c10#1591, _c11#1592]
                                       +- Project [time_stamp#1666, id#1679, _c2#1583 AS dlc#1692, _c3#1584, _c4#1585, _c5#1586, _c6#1587, _c7#1588, _c8#1589, _c9#1590, _c10#1591, _c11#1592]
                                          +- Project [time_stamp#1666, _c1#1582 AS id#1679, _c2#1583, _c3#1584, _c4#1585, _c5#1586, _c6#1587, _c7#1588, _c8#1589, _c9#1590, _c10#1591, _c11#1592]
                                             +- Project [_c0#1581 AS time_stamp#1666, _c1#1582, _c2#1583, _c3#1584, _c4#1585, _c5#1586, _c6#1587, _c7#1588, _c8#1589, _c9#1590, _c10#1591, _c11#1592]
                                                +- Relation[_c0#1581,_c1#1582,_c2#1583,_c3#1584,_c4#1585,_c5#1586,_c6#1587,_c7#1588,_c8#1589,_c9#1590,_c10#1591,_c11#1592] csv
